### ISSUE TITLE
无法拉取到php73镜像

### ISSUE THREAD

**Issue by Airmole** [ballooninmyhand/dnmp#1]
ERROR: pull access denied for registry.cn-hangzhou.aliyuncs.com/balloon/php73, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

$ sudo docker login --username=airmolecheung registry.cn-hangzhou.aliyuncs.com
注册了阿里云，开通容器镜像服务登录后，仍然无法拉取到

**Comment by ballooninmyhand** [comment]
![image](https://user-images.githubusercontent.com/37337177/96070816-7fcd9580-0ed3-11eb-89f8-99776bcff673.png)
仓库类型改为公开，现在可以拉取了

**Comment by ballooninmyhand** [comment]
> ERROR: pull access denied for registry.cn-hangzhou.aliyuncs.com/balloon/php73, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> 
> $ sudo docker login --username=airmolecheung registry.cn-hangzhou.aliyuncs.com
> 注册了阿里云，开通容器镜像服务登录后，仍然无法拉取到

![image](https://user-images.githubusercontent.com/37337177/96071145-18641580-0ed4-11eb-91a4-6c799180c203.png)
仓库类型之前设置成私有，现在改成公开，可以拉取了

**Comment by Airmole** [comment]
> > ERROR: pull access denied for registry.cn-hangzhou.aliyuncs.com/balloon/php73, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> > $ sudo docker login --username=airmolecheung registry.cn-hangzhou.aliyuncs.com
> > 注册了阿里云，开通容器镜像服务登录后，仍然无法拉取到
> 
> ![image](https://user-images.githubusercontent.com/37337177/96071145-18641580-0ed4-11eb-91a4-6c799180c203.png)
> 仓库类型之前设置成私有，现在改成公开，可以拉取了

试了下，现在已经可以了。处理很及时，感谢。
